server:
  port: 10003
  servlet:
    session:
      timeout: 3m
spring:
  application:
    name: DogApplication
  jackson:
    time-zone: GMT+8
  #  热部署
  devtools:
    restart:
      enabled: false
# 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/whitetown_dog?allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(z0DOJl+Ul9KkM9cGdF4MCw==)
    password: ENC(z0DOJl+Ul9KkM9cGdF4MCw==)
    type: com.alibaba.druid.pool.DruidDataSource
# elasticsearch
  elasticsearch:
    rest:
      uris: 192.168.228.128:9201,192.168.228.128:9202
#  mvc:
#    static-path-pattern: /static/**
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#加密密钥 - 可采用启动参数形式传入
jasypt:
  encryptor:
    password: jfy23$#&3&$^%#$GF$
swagger2:
  basePackage: cn.whitetown
  title: whitetown-dog接口文档
  description: whitetown-dog接口文档
  version: 0.0.1
  isOpen: true