server:
  port: 10003
  servlet:
    session:
      timeout: 3m
  tomcat:
    max-connections: 5000
spring:
  application:
    name: DogApplication
  jackson:
    time-zone: GMT+8
  #  热部署
  devtools:
    restart:
      enabled: false
# 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/whitetown_dog?allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ENC(z0DOJl+Ul9KkM9cGdF4MCw==)
    password: ENC(z0DOJl+Ul9KkM9cGdF4MCw==)
    type: com.alibaba.druid.pool.DruidDataSource
# elasticsearch
  elasticsearch:
    rest:
      uris: 172.16.0.190:9203,172.16.0.190:9204
#  redis
  redis:
    cluster:
      nodes: 192.168.228.128:6601,192.168.228.128:6602,192.168.228.128:6603
    lettuce:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 200
        max-wait: 50
# MyBatis plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#加密密钥 - 可采用启动参数形式传入
jasypt:
  encryptor:
    password: jfy23$#&3&$^%#$GF$
# swagger2 - 生产环境关闭
swagger2:
  basePackage: cn.whitetown
  title: whitetown-dog接口文档
  description: whitetown-dog接口文档
  version: 0.0.1
  isOpen: true